### ISSUE TITLE
libcosmic tabs issues

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/cosmic-edit#37]
COSMIC Edit is the first instance of libcosmic tabs needing more refined functionality. 

The design for tabs: https://www.figma.com/file/SkAtS5qlVOGQC0n895AHzX/Design-System-(WIP)?type=design&node-id=7914-5446&mode=design&t=NKlxg637660dOibH-0

Issues

- [ ] Tabs do not contract cleanly. The design suggest moving to a dropdown menu but we should consider other options like horizontal scroll with controls similar to Firefox.
- [ ] Text overlaps the close icon. The design file suggest moving to ellipses.
- [ ] Text on an active tab can overlap the tab boundary
- [x] The document icon is the same for all files I've opened. This doesn't seem useful.
- [x] An unsaved indicator, as described in the design file would be useful
- [x] Tabs look about 10% too tall compared to the design (cosmic-edit [design](https://www.figma.com/file/xAF419Mla74nOx6VznvPQi/COSMIC-Text-editor-MVP-hand-off?node-id=1%3A10884&mode=dev) for additional reference)

@maria-komarova please review and add your thoughts.

![libcosmic-tabs](https://github.com/pop-os/cosmic-edit/assets/3430283/73dde063-4f8c-442a-954f-e9c33177a339)

**Comment by WatchMkr** [comment]
The design has a nice compact tabs concept.

![Image](https://github.com/pop-os/cosmic-edit/assets/3430283/07d25098-919b-43b3-94e2-f829690c8981)

**Comment by maria-komarova** [comment]
We initially designed those tabs as a separate component although they are now combined in the Design system. But there are some differences between when tabs are used to switch between options inside Settings versus when they are used with expanded functionality like in text editor. 
- Text editor tabs have smaller vertical padding (4px - space_xxxs)
- Text editor tabs should have close button as well as an indicator for unsaved changes.

Collapsing tabs to a dropdown is a good solution inside Settings but won't work for tabs that are in Text editor. What we have on that mockup - collapsing file names with ellipses would work better. Or we can follow the same pattern we introduced for window stacks and use the file name fading rather than ellipses, mostly so that more of the word is visible. The rest is already implied as being similar - with arrows on left and right to cycle through the tabs once there isn't enough space to show them all. 
I'm not sure if this pattern is good inside Settings though so we either need to have a different tab variant inside the Design system or just break it into separate widgets. From what I remember it was also combined with Segmented controls in libcosmic?

Icons might still be useful if they are different depending on the file type. I'm not sure if we have those anywhere or can pull universal icons for various programming languages.

**Comment by jackpot51** [comment]
It would be nice if this was broken into separate issues. Some of the problems have been fixed, others need to be fixed in cosmic-edit, others in libcosmic.

**Comment by jackpot51** [comment]
Fixed items so far:

- The document icon is the same for all files I've opened. This doesn't seem useful.
- An unsaved indicator, as described in the design file would be useful
- Tabs look about 10% too tall compared to the design

libcosmic issues:

- Tabs do not contract cleanly. The design suggest moving to a dropdown menu but we should consider other options like horizontal scroll with controls similar to Firefox.
- Text overlaps the close icon. The design file suggest moving to ellipses.
- Text on an active tab can overlap the tab boundary
